apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: haproxy-ingress
  name: haproxy-ingress
spec:
  selector:
    matchLabels:
      k8s-app: haproxy-ingress
  template:
    metadata:
      labels:
        k8s-app: haproxy-ingress
    spec:
      containers:
      - name: haproxy-ingress
        image: quay.io/jcmoraisjr/haproxy-ingress
        args:
        - --default-backend-service=default/default-http-backend
#        - --default-ssl-certificate=$(POD_NAMESPACE)/tls-secret
        - --configmap=default/haproxy-ingress
        ports:
        - name: http-port
          containerPort: 80
        - name: https-port
          containerPort: 443
        - name: stat-port
          containerPort: 1936
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-ingress
  labels:
    k8s-app: haproxy-ingress
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-port
    protocol: TCP
  selector:
    k8s-app: haproxy-ingress
